# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/anujic/Documents/ps_dram_bender/DRAM-Bender/projects/U50-HBM/U50-HBM.srcs/sources_1/ip/microblaze_0/microblaze_0.xci
# IP: The module: 'microblaze_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anujic/Documents/ps_dram_bender/DRAM-Bender/projects/U50-HBM/U50-HBM.gen/sources_1/ip/microblaze_0/microblaze_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/anujic/Documents/ps_dram_bender/DRAM-Bender/projects/U50-HBM/U50-HBM.gen/sources_1/ip/microblaze_0/microblaze_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/anujic/Documents/ps_dram_bender/DRAM-Bender/projects/U50-HBM/U50-HBM.gen/sources_1/ip/microblaze_0/microblaze_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/anujic/Documents/ps_dram_bender/DRAM-Bender/projects/U50-HBM/U50-HBM.srcs/sources_1/ip/microblaze_0/microblaze_0.xci
# IP: The module: 'microblaze_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anujic/Documents/ps_dram_bender/DRAM-Bender/projects/U50-HBM/U50-HBM.gen/sources_1/ip/microblaze_0/microblaze_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/anujic/Documents/ps_dram_bender/DRAM-Bender/projects/U50-HBM/U50-HBM.gen/sources_1/ip/microblaze_0/microblaze_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/anujic/Documents/ps_dram_bender/DRAM-Bender/projects/U50-HBM/U50-HBM.gen/sources_1/ip/microblaze_0/microblaze_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
